# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 11:08
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('county_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
            options={
                'verbose_name_plural': 'Counties',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('ticket_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('error_code', models.CharField(max_length=50)),
                ('report', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('technical_report', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('class_one_enrollment', models.IntegerField()),
                ('present_devices', models.IntegerField()),
                ('zone', models.CharField(max_length=50)),
                ('emmis_code', models.CharField(blank=True, max_length=100, null=True)),
                ('school_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='geoapp.County')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='geoapp.School'),
        ),
    ]
