# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-24 13:18
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.CharField(choices=[('closed', 'Closed'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], max_length=50)),
                ('error_code', models.CharField(max_length=50)),
                ('serial_number', models.CharField(max_length=100)),
                ('agent', models.CharField(max_length=50)),
                ('report', models.TextField()),
                ('technical_report', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_one_enrollment', models.IntegerField()),
                ('present_devices', models.IntegerField()),
                ('sub_county', models.CharField(max_length=50)),
                ('zone', models.CharField(max_length=50)),
                ('emmis_code', models.CharField(max_length=50)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoapp.County')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geoapp.School'),
        ),
    ]
